apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-web
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
